name: Eslint

on:
  pull_request:
    paths:
      - '**.js'

jobs:
  eslint:
    runs-on: ubuntu-24.04

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Setup node'
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: 'eslint'
        run: |
          npm install
          npm run lint