name: Php-cs-fixer

on:
  pull_request:
    paths:
      - '**.php'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-24.04

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'php-cs-fixer'
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --dry-run