name: Phpstan

on:
  pull_request:
    paths:
      - '**.php'

jobs:
  phpstan:
    runs-on: ubuntu-24.04

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: "json,memcached"
          ini-values: "memory_limit=-1"
          coverage: none

      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Install project dependencies'
        run: |
          composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable
          vendor/bin/simple-phpunit install

      - name: phpstan
        env:
          SYMFONY_DEPRECATIONS_HELPER: 'max[indirect]=1'
        run: |
          ./vendor/bin/phpstan --no-interaction --no-progress